name: Build Release For All Platform
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, windows-latest]
        arch: [arm64]

    steps:
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 拉取自身仓库代码
        uses: actions/checkout@main

      - name: 安装依赖
        run: |
          yarn
      
      - name: 构建 ${{ runner.arch }}
        run: |
          yarn make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
