name: Build Release
on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

jobs:
  build:
    name: macOS-arm
    runs-on: macos-14
    permissions:
      contents: write
      packages: write

    steps:
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 拉取自身仓库代码
        uses: actions/checkout@main

      - name: 安装依赖
        run: |
          yarn
      
      - name: 构建 ${{ runner.arch }}
        run: |
          yarn make
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Cleanup Artifacts for MacOs
        run: |
          npx rimraf "dist/!(*.dmg)"
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ runner.arch }}
          path: dist
      - name: release
        uses: softprops/action-gh-release@v0.1.14
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'
